- charts/podiumd/Chart.yaml
- charts/podiumd/README.md
- charts/podiumd/values.yaml
- Openformulieren versie 2.7.8 - [Changelog](https://open-forms.readthedocs.io/en/latest/changelog.html#id3)
- Objecten versie 2.4.4 - [Changelog](https://github.com/maykinmedia/objects-api/blob/stable/2.4.x/CHANGELOG.rst)
- Objecttypen versie 2.2.2 - [Changelog](https://github.com/maykinmedia/objecttypes-api/blob/master/CHANGELOG.rst)
- Opennotificaties versie 1.7.1 - [Changelog](https://github.com/open-zaak/open-notificaties/blob/main/CHANGELOG.rst)
- Openinwoner versie 1.12.2 - [Changelog](https://github.com/maykinmedia/open-inwoner/releases)
- Openzaak versie 1.15.0 - [Changelog](https://github.com/open-zaak/open-zaak/blob/main/CHANGELOG.rst)
- ClamAV versie 1.4.1 -  [Changelog](https://github.com/open-zaak/open-zaak/blob/main/CHANGELOG.rst) - Chart versie 3.2.0 - [chart …
> :bookmark: PodiumD 2.0.0

- charts/podiumd/Chart.yaml
- charts/podiumd/README.md
- charts/podiumd/values.yaml
- Patch openinwoner portaal 2.21.3 - [Release notes](https://github.com/maykinmedia/open-inwoner/releases/tag/v1.21.3)
> :bookmark: portaal openinwoner patch 1.21.3

- .github/workflows/release-test.yaml
- .github/workflows/release.yaml
- charts/podiumd/Chart.yaml
- charts/podiumd/values.yaml
Added Keycloak externalDatabase: host: "" in values.yaml Changed tags: portaal: true in values.yaml
Upgraded the version of Open Formulieren to 2.7.9 in values.yaml Upgraded the version of Keycloak to 21.8.0 in Chart.yaml
> PodiumD release 3.0.0

- .github/CODEOWNERS
- charts/podiumd/Chart.yaml
Use the kiss-frontend chat version 1.0.51.
> fix: use kiss-frontend chart

- .github/workflows/trivy-vuln-scanner.yaml
A vulnerability scanner that scans all the images included in the workflow and provides a report of all the found vulnerabilities
> Vulnerability scanner for images

- .github/workflows/release.yaml
- charts/podiumd/Chart.yaml
- charts/podiumd/README.md
- charts/podiumd/values.yaml
Merge Open Inwoner patch 1.21.5 update from PodiumD 2.0.5 into PodiumD 3.0.6
> chore: merge podiumd 2.0.5

- .github/workflows/release-test.yaml
* Changed name of step 'get latest release commit hash'
* Deleted steps 'get latest release commit hash' and 'delete existing tag if it exists'
* Changed name of the workflow
> Workflow gewijzigd voor het releasen van charts met changelogs 

- charts/podiumd/Chart.yaml
- charts/podiumd/values.yaml
Podiumd-contact versie 0.5.1
https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/releases/tag/v0.5.1
> Release/podiumd 3.0.7

- charts/podiumd/Chart.yaml
- charts/podiumd/README.md
- charts/podiumd/values.yaml
De versie van Open Formulieren moet overeenstemmen met de versie van de 3.3 release.
> Open Formulieren versie naar 2.8.5

- charts/podiumd/Chart.yaml
- charts/podiumd/README.md
- charts/podiumd/templates/api-proxy-deployment.yaml
- charts/podiumd/values.yaml
fixes for apiproxy health check port
> Feat: updates for version 4.0.6

- charts/podiumd/Chart.yaml
- charts/podiumd/values.yaml
PodiumD 4.0.7 patch for Open Formulieren 2.8.9
Solves IN-541
> fix: Open Formulieren patch 2.8.9

- charts/podiumd/Chart.yaml
- charts/podiumd/README.md
- charts/podiumd/templates/openarchiefbeheer-storage.yaml
- charts/podiumd/values.yaml
Aanpassingen: 
* Open-archiefbeheer applicatie toegevoegd aan podiumD chart (staat bij default disabled)
* Readme bijgewerkt met helm-docs gegenereerde values
> :sparkles: Add Open archiefbeheer

- charts/podiumd/Chart.yaml
- charts/podiumd/README.md
- charts/podiumd/values.yaml
- Open Formulieren  (adding to Values.yaml + README.md)
- Open Klant  (adding to Values.yaml + README.md)
- Open Inwoner  (adding to Values.yaml + README.md)
> Adding Setup Configuration

- charts/podiumd/values.yaml
> :memo: [IN-583] Update setup-config example for ZGW-api sets

- charts/podiumd/Chart.yaml
- charts/podiumd/README.md
- charts/podiumd/values.yaml
also implements some maykin fixes
> feat: bump Chart.yaml and brp-personen-mock versions

- charts/brp-personen-mock/Chart.yaml
- charts/brp-personen-mock/templates/deployment.yaml
- charts/monitoring-logging/Chart.yaml
- charts/monitoring-logging/values.yaml
fixes brp-personen-mock deployment labels so that the values from the helper are used properly
> changes for brp personen mock & monitoring+logging

- charts/beproeving/.gitignore
- charts/beproeving/Chart.yaml
- charts/beproeving/README.md
- charts/beproeving/templates/_helpers.tpl
- charts/beproeving/values.yaml
cherry picked met pascal, *nudge*
> feat: add initial beproeving helm chart

- charts/podiumd/values.yaml
uitgetest met mario van het ssc, hij heeft de solr gerelateerde image tags uit de values van de ontw-info omgeving gehaald
deze omgeving is goed ge-upgrade dus de PR kan uit draft
> PodiumD 4.2:  IN-773 solr upgrade

- charts/podiumd/templates/create-required-catalogi.yaml
- charts/podiumd/values.yaml
ik ga deze change uittesten op ontw-icat en heb icatt geinformeerd
> IN-740: make creation of e2e-test zaaktype in openzaak optional in podiumd 4.2

- charts/kiss/values.yaml
- charts/podiumd/Chart.yaml
- charts/podiumd/README.md
- charts/podiumd/templates/create-required-catalogi.yaml
- charts/podiumd/templates/keycloak-config-configmap.yaml
- charts/podiumd/values.yaml
In de [feature/podiumd-4.2](https://github.com/Dimpact-Samenwerking/helm-charts/tree/feature/podiumd-4.2) branch worden alle wijzigingen verzameld die PodiumD 4.2 vormen.
De component wijzigingen willen we in losse branches aanmaken en naar de [feature/podiumd-4.2](https://github.com/Dimpact-Samenwerking/helm-charts/tree/feature/podiumd-4.2) mergen als deze zijn goedgekeurd.
De component wijzigingen moeten we documenteren op verschillende niveaus:
- Component versies en de wijzigingen die daar zijn gemaakt op de [PodiumD 4.2](https://dimpact.atlassian.net/wiki/spaces/PCP/pages/353894412/PodiumD+4.2) confluence pagina.
- Bekende fouten meldingen aan gemeenten op de [PodiumD 4.2: Releasenotitie - Gemeenten](https://dimpact.atlassian.net/wiki/spaces/PCP/pages/453771265/PodiumD+4.2+Releasenoti …
> PodiumD 4.2

- charts/monitoring-logging/Chart.yaml
- charts/monitoring-logging/README.md
- charts/monitoring-logging/values.yaml
* Updated Loki image tag to 3.5.2
* Updated Prometheus image tag to v3.5.0
* Updated Prometheus dependency version to 27.26.0
* Update Loki dependency version to 3.5.2
* Updated README with new version information
> * Changed helm version to 1.0.6
